name: 📄 Update README Projects

on:
  push:
    branches: [main]
    paths:
      - '**/*.ino'
      - '**/README.md'
      - '*/'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run updateReadme script
        run: |
          npm install
          node scripts/updateReadme.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "🔄 Auto-update project list in README.md" || echo "No changes"
          git push
